import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import { Header } from '@/src/components/TheHeader/TheHeader'
import { Footer } from '@/src/components/TheFooter/TheFootr'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'IPR Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
